
text_list = [
    {
      "consent_form_naturalistic": "<h3><p>DARTMOUTH COLLEGE</p> <p>Naturalistic Cognition</p>  <p>RESEARCH PROJECT INFORMATION SHEET</p></h3>" +
      "<p><small><small><small>This research project is being conducted by researchers from the Department of Psychological & Brain Sciences at Dartmouth College, Hanover, NH, USA. This study aims to understand how individuals respond to movies and stories, and how their responses relate to aspects of their personality, cognitive abilities, and other traits. </p>" +
      "Your participation is voluntary. Participation involves watching videos, reading or listening to stories, playing simple video games and other computerized tasks, answering questions about yourself, and similar activities. You may choose to not answer any or all questions concerning personal or demographic information (age, gender, race, ethnicity, location, handedness etc.) as well as your opinions or feelings about the presented photos, audios, videos or any other survey material. However, you may be required to answer third-person questions relating to the task (e.g. ’Was there a social interaction in the presented video?“).  You must be 18 or older to participate. You may immediately end your participation if any aspect of the research procedure makes you too uncomfortable to continue. If you end your participation prematurely due to discomfort or technical difficulties, please contact the researcher to make sure you receive your payment. You may contact the researcher Emily Finn at emily.s.finn@dartmouth.edu.</p>" +
      "The information collected will be anonymous and no identifying information will be stored with the data collected during the experiment. Identifying information will not be used in any presentation or paper written about this project and such presentations will represent the aggregation of data from groups of people. </p>" +
      "Because your responses will not be individually identified, we will not be providing you with personal feedback or referrals based on any of your answers. We will not be monitoring your answers to any items, including questions about suicidality and self-harm, either in real time or after your participation is complete. If you are in crisis, and need immediate support or intervention, call, or go the website of the National Suicide Prevention Lifeline (1-800-273- 8255). Trained crisis workers are available to talk 24 hours a day, 7 days a week.</p>"+
      "The information collected will be anonymous and no identifying information will be stored with the data collected during the experiment. Identifying information will not be used in any presentation or paper written about this project and such presentations will represent the aggregation of data from groups of people. Because your responses will not be individually identified, we will not be providing you with personal feedback or referrals based on any of your answers. We will not be monitoring your answers to any items, including questions about suicidality and self-harm, either in real time or after your participation is complete. If you are in crisis, and need immediate support or intervention, call, or go the website of the National Suicide Prevention Lifeline (1-800-273-8255). Trained crisis workers are available to talk 24 hours a day, 7 days a week. For general information on mental health and to locate treatment services in your area, call the Substance Abuse and Mental Health Services Administration (SAMHSA) Treatment Referral Helpline at 1-800-662-HELP (4357). SAMHSA also has a Behavioral Health Treatment Locator on its website that can be searched by location. "+
      "<p>Questions about this project may be directed to: </p> <p> Emily Finn, Principal Investigator, HB 6207 Moore Hall,Hanover, NH 03755. Email: emily.s.finn@dartmouth.edu </p>"
    },{
        "devices_off_1": "<p>The survey has been optimized for Google Chrome and you may not be able to submit the survey with other browswers, so please switch to Chrome before you begin.</p>",
      "devices_off_2": "<style>p{text-align: left;}</style><p>You must pay full attention for the next 30 minutes, so please<br>  (1) mute all notifications and close open tabs,<br>(2) sit comfortably,<br>  (3) wear glasses or contact lenses if you use them, and <br>  (4) check that all mouse controls work.</p>"
    },{
      "instructions_txt_1": "<p>In this survey, you will watch several short animations (no audio) such as the one above. Each animation has two filled circles moving about on the screen. In some of the animations, the motion can resemble a chase or pursuit-like behavior, and in the others, the movement patterns will be random.<br/><strong>If you do not see the animation above, please exit now - you won't be able to submit the survey to Prolific without this.</strong><br> Before proceeding, please zoom in/out your browser such that the width of the video frame above approximately matches that of a credit card. Now please do not change until the end of the survey.<br> There will be 84 animations in all, and you will be given short breaks to rest your eyes intermittently. Unless you are at one of these breaks, please do not look away from the screen.<br>Press 1 to continue to demo</p>" ,
      "instructions_txt_2": '<div style="width:600px;"> <p>Question 1: Did you see a chase, or were the circles moving randomly? Indicate your choice on the continuous bar below.<br/><br/> The position of the circular green marker on the horizontal bar indicates both (i) what you see and (ii) how confident you are about this. The left and right halves of the bar correspond to random motion and chase, respectively.<br>The closer the marker is placed to the ends of the bar, the higher the confidence about a random motion (left) or chase (right). Similarly, points closer to the centre on the left or right indicate higher uncertainty about random motion or chase, respectively.</p>',
      "instructions_txt_3": 'Which circle did you think was the chaser?<br>Make a guess if you did not see a chase at all.</p><img src="circle_img/black_circle.png" width="20" height="20"><img src="circle_img/grey_circle.png" width="20" height="20" <p>'
    }

   ]
